import type { Metadata } from 'next'
import { Raleway } from 'next/font/google'

import './../sass/globals.sass'
import { GlobalsContextProvider } from '@/context/GlobalsContext'

// const inter = Inter({ subsets: ['latin'] })
const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <GlobalsContextProvider>{children}</GlobalsContextProvider>
      </body>
    </html>
  )
}
